### ISSUE TITLE
graph.removeExports is not a function

### ISSUE THREAD

**Issue by trustmaster** [noflo/noflo-ui#499]
Getting this when trying to pull an updated graph from Github:

```
TypeError: graph.removeExports is not a function
  at resetGraph (https://app.flowhub.io/browser/noflo-ui.js:4778:11)
  at Object.mergeResolveTheirsNaive [as mergeResolveTheirs] (https://app.flowhub.io/browser/noflo-ui.js:4802:3)
  at https://app.flowhub.io/browser/noflo-ui.js:60051:19
  at Object.exports.loadJSON (https://app.flowhub.io/browser/noflo-ui.js:4693:10)
  at handleGraph (https://app.flowhub.io/browser/noflo-ui.js:60042:29)
  at Component.<anonymous> (https://app.flowhub.io/browser/noflo-ui.js:60162:18)
  at task (https://app.flowhub.io/browser/noflo-ui.js:8982:20)
  at resumeTaskQ (https://app.flowhub.io/browser/noflo-ui.js:8612:22)
  at InPort.inPort.process (https://app.flowhub.io/browser/noflo-ui.js:8987:11)
  at InPort.handleSocketEvent (https://app.flowhub.io/browser/noflo-ui.js:5252:14)
  at InternalSocket.<anonymous> (https://app.flowhub.io/browser/noflo-ui.js:5213:22)
  at InternalSocket.Emitter.emit (https://app.flowhub.io/browser/noflo-ui.js:336:20)
  at InternalSocket.regularEmitEvent (https://app.flowhub.io/browser/noflo-ui.js:4867:17)
  at InternalSocket.send (https://app.flowhub.io/browser/noflo-ui.js:4920:17)
  at https://app.flowhub.io/browser/noflo-ui.js:5385:23
  at Array.forEach (native)
  at OutPort.send (https://app.flowhub.io/browser/noflo-ui.js:5380:20)
  at IP.sendTo (https://app.flowhub.io/browser/noflo-ui.js:9122:17)
  at Substream.sendTo (https://app.flowhub.io/browser/noflo-ui.js:9156:12)
  at Substream.sendTo (https://app.flowhub.io/browser/noflo-ui.js:9156:12)
  at StreamSender.flush (https://app.flowhub.io/browser/noflo-ui.js:9294:14)
  at processQueue (https://app.flowhub.io/browser/noflo-ui.js:8544:20)
  at Component.component.afterProcess (https://app.flowhub.io/browser/noflo-ui.js:8572:7)
  at whenDone (https://app.flowhub.io/browser/noflo-ui.js:8934:32)
  at Function.<anonymous> (https://app.flowhub.io/browser/noflo-ui.js:22970:14)
  at https://app.flowhub.io/browser/noflo-ui.js:56032:22
  at Array.forEach (native)
  at Function.pager.trigger (https://app.flowhub.io/browser/noflo-ui.js:56031:28)
  at complete (https://app.flowhub.io/browser/noflo-ui.js:55917:31)
  at Request.callback (https://app.flowhub.io/browser/noflo-ui.js:56980:30)
  at Request.<anonymous> (https://app.flowhub.io/browser/noflo-ui.js:56632:10)
  at Request.Emitter.emit (https://app.flowhub.io/browser/noflo-ui.js:23667:20)
  at XMLHttpRequest.xhr.onreadystatechange (https://app.flowhub.io/browser/noflo-ui.js:57052:10)
```

**Comment by jonnor** [comment]
Looks like a typo in https://github.com/noflo/noflo/blob/master/src/lib/Graph.coffee
should be removeExport instead of removeExports (two places)
