### ISSUE TITLE
Graph width/height props not updated to state

### ISSUE THREAD

**Issue by chrisregnier** [noflo/noflo-ui#909]
The main the-graph:App react component takes width/height props and initializes the graph with the size, but updates aren't reflected in the component's state. The examples in the repo that try to update the size of the graph based on the window thus fail.

I'm trying to fix this and make a PR but none of the build steps actually work from a  clean ubuntu env, so I can't figure out how to actually build and test my changes. 

Here's one of the build errors while trying to build using docker `docker build -t noflo-ui .` from a clean pull of the repo:
```
ERROR in browser/noflo-ui.min.js from Terser
TypeError: Cannot read property 'minify' of undefined
    at minify (/data/node_modules/terser-webpack-plugin/dist/minify.js:175:22)
    at module.exports.errors (/data/node_modules/terser-webpack-plugin/dist/worker.js:13:40)
    at handle (/data/node_modules/worker-farm/lib/child/index.js:44:8)
    at process.<anonymous> (/data/node_modules/worker-farm/lib/child/index.js:51:3)
    at emitTwo (events.js:106:13)
    at process.emit (events.js:191:7)
    at process.nextTick (internal/child_process.js:787:12)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
```
I get the same error when building directly.  I also noticed the npm install within docker also fails cause python isn't avail in the image. 
Is this project being maintained anymore?

Any help would be appreciated.

**Comment by chrisregnier** [comment]
Just bad timing. Looks like a bug in latest terser-webpack-plugin that's affecting others today as well.
Also just realized I opened this bug in the wrong repo. Closing and moving to the-graph
